# This is a basic workflow to help you get started with Actions

name: CI_renamed

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, closed ]

  workflow_dispatch:
    inputs:
      print_tags:
        description: 'True to print to STDOUT xxx'
        required: true
        type: boolean
        default: true
      tags:
        description: 'Test scenario tags'
        required: true
        type: string
        default: qwer

jobs:
  a1:
    runs-on: ubuntu-latest
    steps:
      - name: test_shell
        run: echo "The tags are ${{ inputs.tags }}"
