name: Child Workflow

on:
  workflow_call: # 允许被其他 workflow 调用

jobs:
  child-task1:
    runs-on: ubuntu-latest
    steps:
      - name: Run child step
        run: echo "我是子 Workflow child-task1，我正在执行！"
  child-task11:
    runs-on: ubuntu-latest
    steps:
      - name: Run child step
        run: echo "我是子 Workflow child-task11，我正在执行！"        
  child-task2:
    runs-on: ubuntu-latest
    needs: child-task1
    steps:
      - name: Run child step
        run: echo "我是子 Workflow child-task2，我正在执行！"
