on:
  workflow_dispatch:
    inputs:
      qwer:
        type: string
        description: "test test"
        default: '${{ github.action_repository }}'

name: test0625

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'the input is ${{ github.action_repository }}'
