on:
  pull_request:
    branches: ['main'] 
  pull_request_target:
    branches: ['main']

name: test0625

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'the repo is ${{ github.repository }}'
