on:
  workflow_dispatch: 

name: test0516

env:
  test: ''
  test2: ''
  test3: qwer

jobs:
  test0611:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ env.test || env.test2 || env.test3 }}'
      
