on:
  workflow_dispatch: 
  pull_request_target:
    branches: ['main']

name: test0516

env:
  test: ''
  test2: ''
  test3: qwer

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ env.test || env.test2 || env.test3 }}'
  test2:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ env.test || env.test2 || env.test3 }}'      
      
