on:
  workflow_dispatch:
  issue_comment:
    types: created
  pull_request:
    branches:
      - main

name: test0625

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'the input is ${{ github.action_repository }}'
