name: test0729

on:
  workflow_dispatch:
jobs:
  job_a:
    name: job with continue on error
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: fail step
        run: |
          exit 1
      - name: fail step 2
        run: |
          exit 1
  job_b:
    name: downstream after continue
    runs-on: ubuntu-latest
    needs: [job_a]
    steps:
      - name: success step
        run: |
          echo job_b executed
